spring.application.name=query-service
server.port=8086

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.logforge.common.model.LogEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.logforge.common.model
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=query-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=logforge
spring.data.mongodb.username=logforge
spring.data.mongodb.password=logforge123
spring.data.mongodb.authentication-database=admin

spring.data.redis.host=localhost
spring.data.redis.port=6379

# Max results per query
logforge.query.max-results=500

# WebSocket live tail ? max clients
logforge.query.max-tail-clients=50
