spring.application.name=storage-service
server.port=8084

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=logforge
spring.data.mongodb.username=logforge
spring.data.mongodb.password=logforge123
spring.data.mongodb.authentication-database=admin

spring.kafka.bootstrap-servers=localhost:9092

# Tier boundaries
logforge.storage.hot-ttl-seconds=3600
logforge.storage.warm-ttl-days=30
logforge.storage.cold-base-path=./cold-storage

# Tiering scheduler ? runs every hour
logforge.storage.tiering-interval-ms=3600000